/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoidRouteImport } from './routes/void'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as GroupLinksCodeRouteImport } from './routes/group-links/$code'
import { Route as FriendLinksCodeRouteImport } from './routes/friend-links/$code'
import { Route as DmLinksCodeRouteImport } from './routes/dm-links/$code'
import { Route as ChatConversationIdRouteImport } from './routes/chat/$conversationId'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiNotificationsWsRouteImport } from './routes/api/notifications-ws'
import { Route as ApiRelationshipsIndexRouteImport } from './routes/api/relationships/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiMemoriesIndexRouteImport } from './routes/api/memories/index'
import { Route as ApiGroupsIndexRouteImport } from './routes/api/groups/index'
import { Route as ApiGhostsIndexRouteImport } from './routes/api/ghosts/index'
import { Route as ApiFriendLinksIndexRouteImport } from './routes/api/friend-links/index'
import { Route as ApiDmLinksIndexRouteImport } from './routes/api/dm-links/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiUsersSearchRouteImport } from './routes/api/users/search'
import { Route as ApiSpacesFeedRouteImport } from './routes/api/spaces/feed'
import { Route as ApiRelationshipsRelatedUserIdRouteImport } from './routes/api/relationships/$relatedUserId'
import { Route as ApiNotificationsUnreadCountRouteImport } from './routes/api/notifications/unread-count'
import { Route as ApiNotificationsReadAllRouteImport } from './routes/api/notifications/read-all'
import { Route as ApiNotificationsIdRouteImport } from './routes/api/notifications/$id'
import { Route as ApiMemoriesSearchRouteImport } from './routes/api/memories/search'
import { Route as ApiMemoriesFeedRouteImport } from './routes/api/memories/feed'
import { Route as ApiMemoriesCheckDuplicateRouteImport } from './routes/api/memories/check-duplicate'
import { Route as ApiMemoriesMemoryIdRouteImport } from './routes/api/memories/$memoryId'
import { Route as ApiMcpToolsRouteImport } from './routes/api/mcp/tools'
import { Route as ApiGroupsGroupIdRouteImport } from './routes/api/groups/$groupId'
import { Route as ApiConversationsConversationIdRouteImport } from './routes/api/conversations/$conversationId'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiGhostsConversationsIndexRouteImport } from './routes/api/ghosts/conversations/index'
import { Route as ApiNotificationsIdReadRouteImport } from './routes/api/notifications/$id.read'
import { Route as ApiMemoriesMemoryIdSimilarRouteImport } from './routes/api/memories/$memoryId/similar'
import { Route as ApiMemoriesMemoryIdRateRouteImport } from './routes/api/memories/$memoryId/rate'
import { Route as ApiGroupsGroupIdPermissionsRouteImport } from './routes/api/groups/$groupId.permissions'
import { Route as ApiGroupsGroupIdMembersRouteImport } from './routes/api/groups/$groupId.members'
import { Route as ApiGroupsGroupIdLinksRouteImport } from './routes/api/groups/$groupId.links'
import { Route as ApiGroupLinksCodeRedeemRouteImport } from './routes/api/group-links/$code.redeem'
import { Route as ApiGhostsGhostIdConversationRouteImport } from './routes/api/ghosts/$ghostId.conversation'
import { Route as ApiFriendLinksCodeRedeemRouteImport } from './routes/api/friend-links/$code.redeem'
import { Route as ApiDmLinksCodeRedeemRouteImport } from './routes/api/dm-links/$code.redeem'
import { Route as ApiConversationsConversationIdReadRouteImport } from './routes/api/conversations/$conversationId/read'
import { Route as ApiConversationsConversationIdParticipantsRouteImport } from './routes/api/conversations/$conversationId.participants'
import { Route as ApiConversationsConversationIdMessagesRouteImport } from './routes/api/conversations/$conversationId.messages'
import { Route as ApiConversationsConversationIdLastMessageRouteImport } from './routes/api/conversations/$conversationId.last-message'
import { Route as ApiConversationsConversationIdMessagesIndexRouteImport } from './routes/api/conversations/$conversationId/messages/index'
import { Route as ApiMcpToolsToolNameSchemaRouteImport } from './routes/api/mcp/tools.$toolName.schema'
import { Route as ApiMcpToolsToolNameInvokeRouteImport } from './routes/api/mcp/tools.$toolName.invoke'
import { Route as ApiGroupsGroupIdMembersUserIdRouteImport } from './routes/api/groups/$groupId.members.$userId'
import { Route as ApiGhostsConversationsConversationIdMessagesRouteImport } from './routes/api/ghosts/conversations/$conversationId.messages'
import { Route as ApiConversationsConversationIdMessagesMessageIdRouteImport } from './routes/api/conversations/$conversationId/messages/$messageId'
import { Route as ApiGhostsConversationsConversationIdMessagesStreamRouteImport } from './routes/api/ghosts/conversations/$conversationId.messages.stream'

const VoidRoute = VoidRouteImport.update({
  id: '/void',
  path: '/void',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const GroupLinksCodeRoute = GroupLinksCodeRouteImport.update({
  id: '/group-links/$code',
  path: '/group-links/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendLinksCodeRoute = FriendLinksCodeRouteImport.update({
  id: '/friend-links/$code',
  path: '/friend-links/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DmLinksCodeRoute = DmLinksCodeRouteImport.update({
  id: '/dm-links/$code',
  path: '/dm-links/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsWsRoute = ApiNotificationsWsRouteImport.update({
  id: '/api/notifications-ws',
  path: '/api/notifications-ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipsIndexRoute = ApiRelationshipsIndexRouteImport.update({
  id: '/api/relationships/',
  path: '/api/relationships/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesIndexRoute = ApiMemoriesIndexRouteImport.update({
  id: '/api/memories/',
  path: '/api/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsIndexRoute = ApiGroupsIndexRouteImport.update({
  id: '/api/groups/',
  path: '/api/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGhostsIndexRoute = ApiGhostsIndexRouteImport.update({
  id: '/api/ghosts/',
  path: '/api/ghosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendLinksIndexRoute = ApiFriendLinksIndexRouteImport.update({
  id: '/api/friend-links/',
  path: '/api/friend-links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDmLinksIndexRoute = ApiDmLinksIndexRouteImport.update({
  id: '/api/dm-links/',
  path: '/api/dm-links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSearchRoute = ApiUsersSearchRouteImport.update({
  id: '/api/users/search',
  path: '/api/users/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpacesFeedRoute = ApiSpacesFeedRouteImport.update({
  id: '/api/spaces/feed',
  path: '/api/spaces/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipsRelatedUserIdRoute =
  ApiRelationshipsRelatedUserIdRouteImport.update({
    id: '/api/relationships/$relatedUserId',
    path: '/api/relationships/$relatedUserId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsUnreadCountRoute =
  ApiNotificationsUnreadCountRouteImport.update({
    id: '/api/notifications/unread-count',
    path: '/api/notifications/unread-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsReadAllRoute = ApiNotificationsReadAllRouteImport.update({
  id: '/api/notifications/read-all',
  path: '/api/notifications/read-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIdRoute = ApiNotificationsIdRouteImport.update({
  id: '/api/notifications/$id',
  path: '/api/notifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesSearchRoute = ApiMemoriesSearchRouteImport.update({
  id: '/api/memories/search',
  path: '/api/memories/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesFeedRoute = ApiMemoriesFeedRouteImport.update({
  id: '/api/memories/feed',
  path: '/api/memories/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesCheckDuplicateRoute =
  ApiMemoriesCheckDuplicateRouteImport.update({
    id: '/api/memories/check-duplicate',
    path: '/api/memories/check-duplicate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMemoriesMemoryIdRoute = ApiMemoriesMemoryIdRouteImport.update({
  id: '/api/memories/$memoryId',
  path: '/api/memories/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpToolsRoute = ApiMcpToolsRouteImport.update({
  id: '/api/mcp/tools',
  path: '/api/mcp/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsGroupIdRoute = ApiGroupsGroupIdRouteImport.update({
  id: '/api/groups/$groupId',
  path: '/api/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdRoute =
  ApiConversationsConversationIdRouteImport.update({
    id: '/api/conversations/$conversationId',
    path: '/api/conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGhostsConversationsIndexRoute =
  ApiGhostsConversationsIndexRouteImport.update({
    id: '/api/ghosts/conversations/',
    path: '/api/ghosts/conversations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsIdReadRoute = ApiNotificationsIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiNotificationsIdRoute,
} as any)
const ApiMemoriesMemoryIdSimilarRoute =
  ApiMemoriesMemoryIdSimilarRouteImport.update({
    id: '/similar',
    path: '/similar',
    getParentRoute: () => ApiMemoriesMemoryIdRoute,
  } as any)
const ApiMemoriesMemoryIdRateRoute = ApiMemoriesMemoryIdRateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => ApiMemoriesMemoryIdRoute,
} as any)
const ApiGroupsGroupIdPermissionsRoute =
  ApiGroupsGroupIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => ApiGroupsGroupIdRoute,
  } as any)
const ApiGroupsGroupIdMembersRoute = ApiGroupsGroupIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiGroupsGroupIdRoute,
} as any)
const ApiGroupsGroupIdLinksRoute = ApiGroupsGroupIdLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => ApiGroupsGroupIdRoute,
} as any)
const ApiGroupLinksCodeRedeemRoute = ApiGroupLinksCodeRedeemRouteImport.update({
  id: '/api/group-links/$code/redeem',
  path: '/api/group-links/$code/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGhostsGhostIdConversationRoute =
  ApiGhostsGhostIdConversationRouteImport.update({
    id: '/api/ghosts/$ghostId/conversation',
    path: '/api/ghosts/$ghostId/conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFriendLinksCodeRedeemRoute =
  ApiFriendLinksCodeRedeemRouteImport.update({
    id: '/api/friend-links/$code/redeem',
    path: '/api/friend-links/$code/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDmLinksCodeRedeemRoute = ApiDmLinksCodeRedeemRouteImport.update({
  id: '/api/dm-links/$code/redeem',
  path: '/api/dm-links/$code/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdReadRoute =
  ApiConversationsConversationIdReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdParticipantsRoute =
  ApiConversationsConversationIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdMessagesRoute =
  ApiConversationsConversationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdLastMessageRoute =
  ApiConversationsConversationIdLastMessageRouteImport.update({
    id: '/last-message',
    path: '/last-message',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdMessagesIndexRoute =
  ApiConversationsConversationIdMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ApiConversationsConversationIdMessagesRoute,
  } as any)
const ApiMcpToolsToolNameSchemaRoute =
  ApiMcpToolsToolNameSchemaRouteImport.update({
    id: '/$toolName/schema',
    path: '/$toolName/schema',
    getParentRoute: () => ApiMcpToolsRoute,
  } as any)
const ApiMcpToolsToolNameInvokeRoute =
  ApiMcpToolsToolNameInvokeRouteImport.update({
    id: '/$toolName/invoke',
    path: '/$toolName/invoke',
    getParentRoute: () => ApiMcpToolsRoute,
  } as any)
const ApiGroupsGroupIdMembersUserIdRoute =
  ApiGroupsGroupIdMembersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiGroupsGroupIdMembersRoute,
  } as any)
const ApiGhostsConversationsConversationIdMessagesRoute =
  ApiGhostsConversationsConversationIdMessagesRouteImport.update({
    id: '/api/ghosts/conversations/$conversationId/messages',
    path: '/api/ghosts/conversations/$conversationId/messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsConversationIdMessagesMessageIdRoute =
  ApiConversationsConversationIdMessagesMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => ApiConversationsConversationIdMessagesRoute,
  } as any)
const ApiGhostsConversationsConversationIdMessagesStreamRoute =
  ApiGhostsConversationsConversationIdMessagesStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiGhostsConversationsConversationIdMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/void': typeof VoidRoute
  '/api/notifications-ws': typeof ApiNotificationsWsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ws': typeof ApiWsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/dm-links/$code': typeof DmLinksCodeRoute
  '/friend-links/$code': typeof FriendLinksCodeRoute
  '/group-links/$code': typeof GroupLinksCodeRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/groups/$groupId': typeof ApiGroupsGroupIdRouteWithChildren
  '/api/mcp/tools': typeof ApiMcpToolsRouteWithChildren
  '/api/memories/$memoryId': typeof ApiMemoriesMemoryIdRouteWithChildren
  '/api/memories/check-duplicate': typeof ApiMemoriesCheckDuplicateRoute
  '/api/memories/feed': typeof ApiMemoriesFeedRoute
  '/api/memories/search': typeof ApiMemoriesSearchRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRouteWithChildren
  '/api/notifications/read-all': typeof ApiNotificationsReadAllRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/relationships/$relatedUserId': typeof ApiRelationshipsRelatedUserIdRoute
  '/api/spaces/feed': typeof ApiSpacesFeedRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/dm-links/': typeof ApiDmLinksIndexRoute
  '/api/friend-links/': typeof ApiFriendLinksIndexRoute
  '/api/ghosts/': typeof ApiGhostsIndexRoute
  '/api/groups/': typeof ApiGroupsIndexRoute
  '/api/memories/': typeof ApiMemoriesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/relationships/': typeof ApiRelationshipsIndexRoute
  '/api/conversations/$conversationId/last-message': typeof ApiConversationsConversationIdLastMessageRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRouteWithChildren
  '/api/conversations/$conversationId/participants': typeof ApiConversationsConversationIdParticipantsRoute
  '/api/conversations/$conversationId/read': typeof ApiConversationsConversationIdReadRoute
  '/api/dm-links/$code/redeem': typeof ApiDmLinksCodeRedeemRoute
  '/api/friend-links/$code/redeem': typeof ApiFriendLinksCodeRedeemRoute
  '/api/ghosts/$ghostId/conversation': typeof ApiGhostsGhostIdConversationRoute
  '/api/group-links/$code/redeem': typeof ApiGroupLinksCodeRedeemRoute
  '/api/groups/$groupId/links': typeof ApiGroupsGroupIdLinksRoute
  '/api/groups/$groupId/members': typeof ApiGroupsGroupIdMembersRouteWithChildren
  '/api/groups/$groupId/permissions': typeof ApiGroupsGroupIdPermissionsRoute
  '/api/memories/$memoryId/rate': typeof ApiMemoriesMemoryIdRateRoute
  '/api/memories/$memoryId/similar': typeof ApiMemoriesMemoryIdSimilarRoute
  '/api/notifications/$id/read': typeof ApiNotificationsIdReadRoute
  '/api/ghosts/conversations/': typeof ApiGhostsConversationsIndexRoute
  '/api/conversations/$conversationId/messages/$messageId': typeof ApiConversationsConversationIdMessagesMessageIdRoute
  '/api/ghosts/conversations/$conversationId/messages': typeof ApiGhostsConversationsConversationIdMessagesRouteWithChildren
  '/api/groups/$groupId/members/$userId': typeof ApiGroupsGroupIdMembersUserIdRoute
  '/api/mcp/tools/$toolName/invoke': typeof ApiMcpToolsToolNameInvokeRoute
  '/api/mcp/tools/$toolName/schema': typeof ApiMcpToolsToolNameSchemaRoute
  '/api/conversations/$conversationId/messages/': typeof ApiConversationsConversationIdMessagesIndexRoute
  '/api/ghosts/conversations/$conversationId/messages/stream': typeof ApiGhostsConversationsConversationIdMessagesStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/void': typeof VoidRoute
  '/api/notifications-ws': typeof ApiNotificationsWsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ws': typeof ApiWsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/dm-links/$code': typeof DmLinksCodeRoute
  '/friend-links/$code': typeof FriendLinksCodeRoute
  '/group-links/$code': typeof GroupLinksCodeRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/groups/$groupId': typeof ApiGroupsGroupIdRouteWithChildren
  '/api/mcp/tools': typeof ApiMcpToolsRouteWithChildren
  '/api/memories/$memoryId': typeof ApiMemoriesMemoryIdRouteWithChildren
  '/api/memories/check-duplicate': typeof ApiMemoriesCheckDuplicateRoute
  '/api/memories/feed': typeof ApiMemoriesFeedRoute
  '/api/memories/search': typeof ApiMemoriesSearchRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRouteWithChildren
  '/api/notifications/read-all': typeof ApiNotificationsReadAllRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/relationships/$relatedUserId': typeof ApiRelationshipsRelatedUserIdRoute
  '/api/spaces/feed': typeof ApiSpacesFeedRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/dm-links': typeof ApiDmLinksIndexRoute
  '/api/friend-links': typeof ApiFriendLinksIndexRoute
  '/api/ghosts': typeof ApiGhostsIndexRoute
  '/api/groups': typeof ApiGroupsIndexRoute
  '/api/memories': typeof ApiMemoriesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/relationships': typeof ApiRelationshipsIndexRoute
  '/api/conversations/$conversationId/last-message': typeof ApiConversationsConversationIdLastMessageRoute
  '/api/conversations/$conversationId/participants': typeof ApiConversationsConversationIdParticipantsRoute
  '/api/conversations/$conversationId/read': typeof ApiConversationsConversationIdReadRoute
  '/api/dm-links/$code/redeem': typeof ApiDmLinksCodeRedeemRoute
  '/api/friend-links/$code/redeem': typeof ApiFriendLinksCodeRedeemRoute
  '/api/ghosts/$ghostId/conversation': typeof ApiGhostsGhostIdConversationRoute
  '/api/group-links/$code/redeem': typeof ApiGroupLinksCodeRedeemRoute
  '/api/groups/$groupId/links': typeof ApiGroupsGroupIdLinksRoute
  '/api/groups/$groupId/members': typeof ApiGroupsGroupIdMembersRouteWithChildren
  '/api/groups/$groupId/permissions': typeof ApiGroupsGroupIdPermissionsRoute
  '/api/memories/$memoryId/rate': typeof ApiMemoriesMemoryIdRateRoute
  '/api/memories/$memoryId/similar': typeof ApiMemoriesMemoryIdSimilarRoute
  '/api/notifications/$id/read': typeof ApiNotificationsIdReadRoute
  '/api/ghosts/conversations': typeof ApiGhostsConversationsIndexRoute
  '/api/conversations/$conversationId/messages/$messageId': typeof ApiConversationsConversationIdMessagesMessageIdRoute
  '/api/ghosts/conversations/$conversationId/messages': typeof ApiGhostsConversationsConversationIdMessagesRouteWithChildren
  '/api/groups/$groupId/members/$userId': typeof ApiGroupsGroupIdMembersUserIdRoute
  '/api/mcp/tools/$toolName/invoke': typeof ApiMcpToolsToolNameInvokeRoute
  '/api/mcp/tools/$toolName/schema': typeof ApiMcpToolsToolNameSchemaRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesIndexRoute
  '/api/ghosts/conversations/$conversationId/messages/stream': typeof ApiGhostsConversationsConversationIdMessagesStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/void': typeof VoidRoute
  '/api/notifications-ws': typeof ApiNotificationsWsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ws': typeof ApiWsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/dm-links/$code': typeof DmLinksCodeRoute
  '/friend-links/$code': typeof FriendLinksCodeRoute
  '/group-links/$code': typeof GroupLinksCodeRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/groups/$groupId': typeof ApiGroupsGroupIdRouteWithChildren
  '/api/mcp/tools': typeof ApiMcpToolsRouteWithChildren
  '/api/memories/$memoryId': typeof ApiMemoriesMemoryIdRouteWithChildren
  '/api/memories/check-duplicate': typeof ApiMemoriesCheckDuplicateRoute
  '/api/memories/feed': typeof ApiMemoriesFeedRoute
  '/api/memories/search': typeof ApiMemoriesSearchRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRouteWithChildren
  '/api/notifications/read-all': typeof ApiNotificationsReadAllRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/relationships/$relatedUserId': typeof ApiRelationshipsRelatedUserIdRoute
  '/api/spaces/feed': typeof ApiSpacesFeedRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/dm-links/': typeof ApiDmLinksIndexRoute
  '/api/friend-links/': typeof ApiFriendLinksIndexRoute
  '/api/ghosts/': typeof ApiGhostsIndexRoute
  '/api/groups/': typeof ApiGroupsIndexRoute
  '/api/memories/': typeof ApiMemoriesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/relationships/': typeof ApiRelationshipsIndexRoute
  '/api/conversations/$conversationId/last-message': typeof ApiConversationsConversationIdLastMessageRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRouteWithChildren
  '/api/conversations/$conversationId/participants': typeof ApiConversationsConversationIdParticipantsRoute
  '/api/conversations/$conversationId/read': typeof ApiConversationsConversationIdReadRoute
  '/api/dm-links/$code/redeem': typeof ApiDmLinksCodeRedeemRoute
  '/api/friend-links/$code/redeem': typeof ApiFriendLinksCodeRedeemRoute
  '/api/ghosts/$ghostId/conversation': typeof ApiGhostsGhostIdConversationRoute
  '/api/group-links/$code/redeem': typeof ApiGroupLinksCodeRedeemRoute
  '/api/groups/$groupId/links': typeof ApiGroupsGroupIdLinksRoute
  '/api/groups/$groupId/members': typeof ApiGroupsGroupIdMembersRouteWithChildren
  '/api/groups/$groupId/permissions': typeof ApiGroupsGroupIdPermissionsRoute
  '/api/memories/$memoryId/rate': typeof ApiMemoriesMemoryIdRateRoute
  '/api/memories/$memoryId/similar': typeof ApiMemoriesMemoryIdSimilarRoute
  '/api/notifications/$id/read': typeof ApiNotificationsIdReadRoute
  '/api/ghosts/conversations/': typeof ApiGhostsConversationsIndexRoute
  '/api/conversations/$conversationId/messages/$messageId': typeof ApiConversationsConversationIdMessagesMessageIdRoute
  '/api/ghosts/conversations/$conversationId/messages': typeof ApiGhostsConversationsConversationIdMessagesRouteWithChildren
  '/api/groups/$groupId/members/$userId': typeof ApiGroupsGroupIdMembersUserIdRoute
  '/api/mcp/tools/$toolName/invoke': typeof ApiMcpToolsToolNameInvokeRoute
  '/api/mcp/tools/$toolName/schema': typeof ApiMcpToolsToolNameSchemaRoute
  '/api/conversations/$conversationId/messages/': typeof ApiConversationsConversationIdMessagesIndexRoute
  '/api/ghosts/conversations/$conversationId/messages/stream': typeof ApiGhostsConversationsConversationIdMessagesStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/friends'
    | '/memories'
    | '/settings'
    | '/void'
    | '/api/notifications-ws'
    | '/api/search'
    | '/api/upload'
    | '/api/ws'
    | '/chat/$conversationId'
    | '/dm-links/$code'
    | '/friend-links/$code'
    | '/group-links/$code'
    | '/chat/'
    | '/settings/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/conversations/$conversationId'
    | '/api/groups/$groupId'
    | '/api/mcp/tools'
    | '/api/memories/$memoryId'
    | '/api/memories/check-duplicate'
    | '/api/memories/feed'
    | '/api/memories/search'
    | '/api/notifications/$id'
    | '/api/notifications/read-all'
    | '/api/notifications/unread-count'
    | '/api/relationships/$relatedUserId'
    | '/api/spaces/feed'
    | '/api/users/search'
    | '/api/conversations/'
    | '/api/dm-links/'
    | '/api/friend-links/'
    | '/api/ghosts/'
    | '/api/groups/'
    | '/api/memories/'
    | '/api/notifications/'
    | '/api/relationships/'
    | '/api/conversations/$conversationId/last-message'
    | '/api/conversations/$conversationId/messages'
    | '/api/conversations/$conversationId/participants'
    | '/api/conversations/$conversationId/read'
    | '/api/dm-links/$code/redeem'
    | '/api/friend-links/$code/redeem'
    | '/api/ghosts/$ghostId/conversation'
    | '/api/group-links/$code/redeem'
    | '/api/groups/$groupId/links'
    | '/api/groups/$groupId/members'
    | '/api/groups/$groupId/permissions'
    | '/api/memories/$memoryId/rate'
    | '/api/memories/$memoryId/similar'
    | '/api/notifications/$id/read'
    | '/api/ghosts/conversations/'
    | '/api/conversations/$conversationId/messages/$messageId'
    | '/api/ghosts/conversations/$conversationId/messages'
    | '/api/groups/$groupId/members/$userId'
    | '/api/mcp/tools/$toolName/invoke'
    | '/api/mcp/tools/$toolName/schema'
    | '/api/conversations/$conversationId/messages/'
    | '/api/ghosts/conversations/$conversationId/messages/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/friends'
    | '/memories'
    | '/void'
    | '/api/notifications-ws'
    | '/api/search'
    | '/api/upload'
    | '/api/ws'
    | '/chat/$conversationId'
    | '/dm-links/$code'
    | '/friend-links/$code'
    | '/group-links/$code'
    | '/chat'
    | '/settings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/conversations/$conversationId'
    | '/api/groups/$groupId'
    | '/api/mcp/tools'
    | '/api/memories/$memoryId'
    | '/api/memories/check-duplicate'
    | '/api/memories/feed'
    | '/api/memories/search'
    | '/api/notifications/$id'
    | '/api/notifications/read-all'
    | '/api/notifications/unread-count'
    | '/api/relationships/$relatedUserId'
    | '/api/spaces/feed'
    | '/api/users/search'
    | '/api/conversations'
    | '/api/dm-links'
    | '/api/friend-links'
    | '/api/ghosts'
    | '/api/groups'
    | '/api/memories'
    | '/api/notifications'
    | '/api/relationships'
    | '/api/conversations/$conversationId/last-message'
    | '/api/conversations/$conversationId/participants'
    | '/api/conversations/$conversationId/read'
    | '/api/dm-links/$code/redeem'
    | '/api/friend-links/$code/redeem'
    | '/api/ghosts/$ghostId/conversation'
    | '/api/group-links/$code/redeem'
    | '/api/groups/$groupId/links'
    | '/api/groups/$groupId/members'
    | '/api/groups/$groupId/permissions'
    | '/api/memories/$memoryId/rate'
    | '/api/memories/$memoryId/similar'
    | '/api/notifications/$id/read'
    | '/api/ghosts/conversations'
    | '/api/conversations/$conversationId/messages/$messageId'
    | '/api/ghosts/conversations/$conversationId/messages'
    | '/api/groups/$groupId/members/$userId'
    | '/api/mcp/tools/$toolName/invoke'
    | '/api/mcp/tools/$toolName/schema'
    | '/api/conversations/$conversationId/messages'
    | '/api/ghosts/conversations/$conversationId/messages/stream'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/friends'
    | '/memories'
    | '/settings'
    | '/void'
    | '/api/notifications-ws'
    | '/api/search'
    | '/api/upload'
    | '/api/ws'
    | '/chat/$conversationId'
    | '/dm-links/$code'
    | '/friend-links/$code'
    | '/group-links/$code'
    | '/chat/'
    | '/settings/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/conversations/$conversationId'
    | '/api/groups/$groupId'
    | '/api/mcp/tools'
    | '/api/memories/$memoryId'
    | '/api/memories/check-duplicate'
    | '/api/memories/feed'
    | '/api/memories/search'
    | '/api/notifications/$id'
    | '/api/notifications/read-all'
    | '/api/notifications/unread-count'
    | '/api/relationships/$relatedUserId'
    | '/api/spaces/feed'
    | '/api/users/search'
    | '/api/conversations/'
    | '/api/dm-links/'
    | '/api/friend-links/'
    | '/api/ghosts/'
    | '/api/groups/'
    | '/api/memories/'
    | '/api/notifications/'
    | '/api/relationships/'
    | '/api/conversations/$conversationId/last-message'
    | '/api/conversations/$conversationId/messages'
    | '/api/conversations/$conversationId/participants'
    | '/api/conversations/$conversationId/read'
    | '/api/dm-links/$code/redeem'
    | '/api/friend-links/$code/redeem'
    | '/api/ghosts/$ghostId/conversation'
    | '/api/group-links/$code/redeem'
    | '/api/groups/$groupId/links'
    | '/api/groups/$groupId/members'
    | '/api/groups/$groupId/permissions'
    | '/api/memories/$memoryId/rate'
    | '/api/memories/$memoryId/similar'
    | '/api/notifications/$id/read'
    | '/api/ghosts/conversations/'
    | '/api/conversations/$conversationId/messages/$messageId'
    | '/api/ghosts/conversations/$conversationId/messages'
    | '/api/groups/$groupId/members/$userId'
    | '/api/mcp/tools/$toolName/invoke'
    | '/api/mcp/tools/$toolName/schema'
    | '/api/conversations/$conversationId/messages/'
    | '/api/ghosts/conversations/$conversationId/messages/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  MemoriesRoute: typeof MemoriesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  VoidRoute: typeof VoidRoute
  ApiNotificationsWsRoute: typeof ApiNotificationsWsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWsRoute: typeof ApiWsRoute
  DmLinksCodeRoute: typeof DmLinksCodeRoute
  FriendLinksCodeRoute: typeof FriendLinksCodeRoute
  GroupLinksCodeRoute: typeof GroupLinksCodeRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiConversationsConversationIdRoute: typeof ApiConversationsConversationIdRouteWithChildren
  ApiGroupsGroupIdRoute: typeof ApiGroupsGroupIdRouteWithChildren
  ApiMcpToolsRoute: typeof ApiMcpToolsRouteWithChildren
  ApiMemoriesMemoryIdRoute: typeof ApiMemoriesMemoryIdRouteWithChildren
  ApiMemoriesCheckDuplicateRoute: typeof ApiMemoriesCheckDuplicateRoute
  ApiMemoriesFeedRoute: typeof ApiMemoriesFeedRoute
  ApiMemoriesSearchRoute: typeof ApiMemoriesSearchRoute
  ApiNotificationsIdRoute: typeof ApiNotificationsIdRouteWithChildren
  ApiNotificationsReadAllRoute: typeof ApiNotificationsReadAllRoute
  ApiNotificationsUnreadCountRoute: typeof ApiNotificationsUnreadCountRoute
  ApiRelationshipsRelatedUserIdRoute: typeof ApiRelationshipsRelatedUserIdRoute
  ApiSpacesFeedRoute: typeof ApiSpacesFeedRoute
  ApiUsersSearchRoute: typeof ApiUsersSearchRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiDmLinksIndexRoute: typeof ApiDmLinksIndexRoute
  ApiFriendLinksIndexRoute: typeof ApiFriendLinksIndexRoute
  ApiGhostsIndexRoute: typeof ApiGhostsIndexRoute
  ApiGroupsIndexRoute: typeof ApiGroupsIndexRoute
  ApiMemoriesIndexRoute: typeof ApiMemoriesIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiRelationshipsIndexRoute: typeof ApiRelationshipsIndexRoute
  ApiDmLinksCodeRedeemRoute: typeof ApiDmLinksCodeRedeemRoute
  ApiFriendLinksCodeRedeemRoute: typeof ApiFriendLinksCodeRedeemRoute
  ApiGhostsGhostIdConversationRoute: typeof ApiGhostsGhostIdConversationRoute
  ApiGroupLinksCodeRedeemRoute: typeof ApiGroupLinksCodeRedeemRoute
  ApiGhostsConversationsIndexRoute: typeof ApiGhostsConversationsIndexRoute
  ApiGhostsConversationsConversationIdMessagesRoute: typeof ApiGhostsConversationsConversationIdMessagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/void': {
      id: '/void'
      path: '/void'
      fullPath: '/void'
      preLoaderRoute: typeof VoidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/group-links/$code': {
      id: '/group-links/$code'
      path: '/group-links/$code'
      fullPath: '/group-links/$code'
      preLoaderRoute: typeof GroupLinksCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-links/$code': {
      id: '/friend-links/$code'
      path: '/friend-links/$code'
      fullPath: '/friend-links/$code'
      preLoaderRoute: typeof FriendLinksCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm-links/$code': {
      id: '/dm-links/$code'
      path: '/dm-links/$code'
      fullPath: '/dm-links/$code'
      preLoaderRoute: typeof DmLinksCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications-ws': {
      id: '/api/notifications-ws'
      path: '/api/notifications-ws'
      fullPath: '/api/notifications-ws'
      preLoaderRoute: typeof ApiNotificationsWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationships/': {
      id: '/api/relationships/'
      path: '/api/relationships'
      fullPath: '/api/relationships/'
      preLoaderRoute: typeof ApiRelationshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/': {
      id: '/api/memories/'
      path: '/api/memories'
      fullPath: '/api/memories/'
      preLoaderRoute: typeof ApiMemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/': {
      id: '/api/groups/'
      path: '/api/groups'
      fullPath: '/api/groups/'
      preLoaderRoute: typeof ApiGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ghosts/': {
      id: '/api/ghosts/'
      path: '/api/ghosts'
      fullPath: '/api/ghosts/'
      preLoaderRoute: typeof ApiGhostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friend-links/': {
      id: '/api/friend-links/'
      path: '/api/friend-links'
      fullPath: '/api/friend-links/'
      preLoaderRoute: typeof ApiFriendLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dm-links/': {
      id: '/api/dm-links/'
      path: '/api/dm-links'
      fullPath: '/api/dm-links/'
      preLoaderRoute: typeof ApiDmLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/search': {
      id: '/api/users/search'
      path: '/api/users/search'
      fullPath: '/api/users/search'
      preLoaderRoute: typeof ApiUsersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spaces/feed': {
      id: '/api/spaces/feed'
      path: '/api/spaces/feed'
      fullPath: '/api/spaces/feed'
      preLoaderRoute: typeof ApiSpacesFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationships/$relatedUserId': {
      id: '/api/relationships/$relatedUserId'
      path: '/api/relationships/$relatedUserId'
      fullPath: '/api/relationships/$relatedUserId'
      preLoaderRoute: typeof ApiRelationshipsRelatedUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/unread-count': {
      id: '/api/notifications/unread-count'
      path: '/api/notifications/unread-count'
      fullPath: '/api/notifications/unread-count'
      preLoaderRoute: typeof ApiNotificationsUnreadCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/read-all': {
      id: '/api/notifications/read-all'
      path: '/api/notifications/read-all'
      fullPath: '/api/notifications/read-all'
      preLoaderRoute: typeof ApiNotificationsReadAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/$id': {
      id: '/api/notifications/$id'
      path: '/api/notifications/$id'
      fullPath: '/api/notifications/$id'
      preLoaderRoute: typeof ApiNotificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/search': {
      id: '/api/memories/search'
      path: '/api/memories/search'
      fullPath: '/api/memories/search'
      preLoaderRoute: typeof ApiMemoriesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/feed': {
      id: '/api/memories/feed'
      path: '/api/memories/feed'
      fullPath: '/api/memories/feed'
      preLoaderRoute: typeof ApiMemoriesFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/check-duplicate': {
      id: '/api/memories/check-duplicate'
      path: '/api/memories/check-duplicate'
      fullPath: '/api/memories/check-duplicate'
      preLoaderRoute: typeof ApiMemoriesCheckDuplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/$memoryId': {
      id: '/api/memories/$memoryId'
      path: '/api/memories/$memoryId'
      fullPath: '/api/memories/$memoryId'
      preLoaderRoute: typeof ApiMemoriesMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/tools': {
      id: '/api/mcp/tools'
      path: '/api/mcp/tools'
      fullPath: '/api/mcp/tools'
      preLoaderRoute: typeof ApiMcpToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/$groupId': {
      id: '/api/groups/$groupId'
      path: '/api/groups/$groupId'
      fullPath: '/api/groups/$groupId'
      preLoaderRoute: typeof ApiGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId': {
      id: '/api/conversations/$conversationId'
      path: '/api/conversations/$conversationId'
      fullPath: '/api/conversations/$conversationId'
      preLoaderRoute: typeof ApiConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ghosts/conversations/': {
      id: '/api/ghosts/conversations/'
      path: '/api/ghosts/conversations'
      fullPath: '/api/ghosts/conversations/'
      preLoaderRoute: typeof ApiGhostsConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/$id/read': {
      id: '/api/notifications/$id/read'
      path: '/read'
      fullPath: '/api/notifications/$id/read'
      preLoaderRoute: typeof ApiNotificationsIdReadRouteImport
      parentRoute: typeof ApiNotificationsIdRoute
    }
    '/api/memories/$memoryId/similar': {
      id: '/api/memories/$memoryId/similar'
      path: '/similar'
      fullPath: '/api/memories/$memoryId/similar'
      preLoaderRoute: typeof ApiMemoriesMemoryIdSimilarRouteImport
      parentRoute: typeof ApiMemoriesMemoryIdRoute
    }
    '/api/memories/$memoryId/rate': {
      id: '/api/memories/$memoryId/rate'
      path: '/rate'
      fullPath: '/api/memories/$memoryId/rate'
      preLoaderRoute: typeof ApiMemoriesMemoryIdRateRouteImport
      parentRoute: typeof ApiMemoriesMemoryIdRoute
    }
    '/api/groups/$groupId/permissions': {
      id: '/api/groups/$groupId/permissions'
      path: '/permissions'
      fullPath: '/api/groups/$groupId/permissions'
      preLoaderRoute: typeof ApiGroupsGroupIdPermissionsRouteImport
      parentRoute: typeof ApiGroupsGroupIdRoute
    }
    '/api/groups/$groupId/members': {
      id: '/api/groups/$groupId/members'
      path: '/members'
      fullPath: '/api/groups/$groupId/members'
      preLoaderRoute: typeof ApiGroupsGroupIdMembersRouteImport
      parentRoute: typeof ApiGroupsGroupIdRoute
    }
    '/api/groups/$groupId/links': {
      id: '/api/groups/$groupId/links'
      path: '/links'
      fullPath: '/api/groups/$groupId/links'
      preLoaderRoute: typeof ApiGroupsGroupIdLinksRouteImport
      parentRoute: typeof ApiGroupsGroupIdRoute
    }
    '/api/group-links/$code/redeem': {
      id: '/api/group-links/$code/redeem'
      path: '/api/group-links/$code/redeem'
      fullPath: '/api/group-links/$code/redeem'
      preLoaderRoute: typeof ApiGroupLinksCodeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ghosts/$ghostId/conversation': {
      id: '/api/ghosts/$ghostId/conversation'
      path: '/api/ghosts/$ghostId/conversation'
      fullPath: '/api/ghosts/$ghostId/conversation'
      preLoaderRoute: typeof ApiGhostsGhostIdConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friend-links/$code/redeem': {
      id: '/api/friend-links/$code/redeem'
      path: '/api/friend-links/$code/redeem'
      fullPath: '/api/friend-links/$code/redeem'
      preLoaderRoute: typeof ApiFriendLinksCodeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dm-links/$code/redeem': {
      id: '/api/dm-links/$code/redeem'
      path: '/api/dm-links/$code/redeem'
      fullPath: '/api/dm-links/$code/redeem'
      preLoaderRoute: typeof ApiDmLinksCodeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId/read': {
      id: '/api/conversations/$conversationId/read'
      path: '/read'
      fullPath: '/api/conversations/$conversationId/read'
      preLoaderRoute: typeof ApiConversationsConversationIdReadRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/participants': {
      id: '/api/conversations/$conversationId/participants'
      path: '/participants'
      fullPath: '/api/conversations/$conversationId/participants'
      preLoaderRoute: typeof ApiConversationsConversationIdParticipantsRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/messages': {
      id: '/api/conversations/$conversationId/messages'
      path: '/messages'
      fullPath: '/api/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/last-message': {
      id: '/api/conversations/$conversationId/last-message'
      path: '/last-message'
      fullPath: '/api/conversations/$conversationId/last-message'
      preLoaderRoute: typeof ApiConversationsConversationIdLastMessageRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/messages/': {
      id: '/api/conversations/$conversationId/messages/'
      path: '/'
      fullPath: '/api/conversations/$conversationId/messages/'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesIndexRouteImport
      parentRoute: typeof ApiConversationsConversationIdMessagesRoute
    }
    '/api/mcp/tools/$toolName/schema': {
      id: '/api/mcp/tools/$toolName/schema'
      path: '/$toolName/schema'
      fullPath: '/api/mcp/tools/$toolName/schema'
      preLoaderRoute: typeof ApiMcpToolsToolNameSchemaRouteImport
      parentRoute: typeof ApiMcpToolsRoute
    }
    '/api/mcp/tools/$toolName/invoke': {
      id: '/api/mcp/tools/$toolName/invoke'
      path: '/$toolName/invoke'
      fullPath: '/api/mcp/tools/$toolName/invoke'
      preLoaderRoute: typeof ApiMcpToolsToolNameInvokeRouteImport
      parentRoute: typeof ApiMcpToolsRoute
    }
    '/api/groups/$groupId/members/$userId': {
      id: '/api/groups/$groupId/members/$userId'
      path: '/$userId'
      fullPath: '/api/groups/$groupId/members/$userId'
      preLoaderRoute: typeof ApiGroupsGroupIdMembersUserIdRouteImport
      parentRoute: typeof ApiGroupsGroupIdMembersRoute
    }
    '/api/ghosts/conversations/$conversationId/messages': {
      id: '/api/ghosts/conversations/$conversationId/messages'
      path: '/api/ghosts/conversations/$conversationId/messages'
      fullPath: '/api/ghosts/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiGhostsConversationsConversationIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId/messages/$messageId': {
      id: '/api/conversations/$conversationId/messages/$messageId'
      path: '/$messageId'
      fullPath: '/api/conversations/$conversationId/messages/$messageId'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesMessageIdRouteImport
      parentRoute: typeof ApiConversationsConversationIdMessagesRoute
    }
    '/api/ghosts/conversations/$conversationId/messages/stream': {
      id: '/api/ghosts/conversations/$conversationId/messages/stream'
      path: '/stream'
      fullPath: '/api/ghosts/conversations/$conversationId/messages/stream'
      preLoaderRoute: typeof ApiGhostsConversationsConversationIdMessagesStreamRouteImport
      parentRoute: typeof ApiGhostsConversationsConversationIdMessagesRoute
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiConversationsConversationIdMessagesRouteChildren {
  ApiConversationsConversationIdMessagesMessageIdRoute: typeof ApiConversationsConversationIdMessagesMessageIdRoute
  ApiConversationsConversationIdMessagesIndexRoute: typeof ApiConversationsConversationIdMessagesIndexRoute
}

const ApiConversationsConversationIdMessagesRouteChildren: ApiConversationsConversationIdMessagesRouteChildren =
  {
    ApiConversationsConversationIdMessagesMessageIdRoute:
      ApiConversationsConversationIdMessagesMessageIdRoute,
    ApiConversationsConversationIdMessagesIndexRoute:
      ApiConversationsConversationIdMessagesIndexRoute,
  }

const ApiConversationsConversationIdMessagesRouteWithChildren =
  ApiConversationsConversationIdMessagesRoute._addFileChildren(
    ApiConversationsConversationIdMessagesRouteChildren,
  )

interface ApiConversationsConversationIdRouteChildren {
  ApiConversationsConversationIdLastMessageRoute: typeof ApiConversationsConversationIdLastMessageRoute
  ApiConversationsConversationIdMessagesRoute: typeof ApiConversationsConversationIdMessagesRouteWithChildren
  ApiConversationsConversationIdParticipantsRoute: typeof ApiConversationsConversationIdParticipantsRoute
  ApiConversationsConversationIdReadRoute: typeof ApiConversationsConversationIdReadRoute
}

const ApiConversationsConversationIdRouteChildren: ApiConversationsConversationIdRouteChildren =
  {
    ApiConversationsConversationIdLastMessageRoute:
      ApiConversationsConversationIdLastMessageRoute,
    ApiConversationsConversationIdMessagesRoute:
      ApiConversationsConversationIdMessagesRouteWithChildren,
    ApiConversationsConversationIdParticipantsRoute:
      ApiConversationsConversationIdParticipantsRoute,
    ApiConversationsConversationIdReadRoute:
      ApiConversationsConversationIdReadRoute,
  }

const ApiConversationsConversationIdRouteWithChildren =
  ApiConversationsConversationIdRoute._addFileChildren(
    ApiConversationsConversationIdRouteChildren,
  )

interface ApiGroupsGroupIdMembersRouteChildren {
  ApiGroupsGroupIdMembersUserIdRoute: typeof ApiGroupsGroupIdMembersUserIdRoute
}

const ApiGroupsGroupIdMembersRouteChildren: ApiGroupsGroupIdMembersRouteChildren =
  {
    ApiGroupsGroupIdMembersUserIdRoute: ApiGroupsGroupIdMembersUserIdRoute,
  }

const ApiGroupsGroupIdMembersRouteWithChildren =
  ApiGroupsGroupIdMembersRoute._addFileChildren(
    ApiGroupsGroupIdMembersRouteChildren,
  )

interface ApiGroupsGroupIdRouteChildren {
  ApiGroupsGroupIdLinksRoute: typeof ApiGroupsGroupIdLinksRoute
  ApiGroupsGroupIdMembersRoute: typeof ApiGroupsGroupIdMembersRouteWithChildren
  ApiGroupsGroupIdPermissionsRoute: typeof ApiGroupsGroupIdPermissionsRoute
}

const ApiGroupsGroupIdRouteChildren: ApiGroupsGroupIdRouteChildren = {
  ApiGroupsGroupIdLinksRoute: ApiGroupsGroupIdLinksRoute,
  ApiGroupsGroupIdMembersRoute: ApiGroupsGroupIdMembersRouteWithChildren,
  ApiGroupsGroupIdPermissionsRoute: ApiGroupsGroupIdPermissionsRoute,
}

const ApiGroupsGroupIdRouteWithChildren =
  ApiGroupsGroupIdRoute._addFileChildren(ApiGroupsGroupIdRouteChildren)

interface ApiMcpToolsRouteChildren {
  ApiMcpToolsToolNameInvokeRoute: typeof ApiMcpToolsToolNameInvokeRoute
  ApiMcpToolsToolNameSchemaRoute: typeof ApiMcpToolsToolNameSchemaRoute
}

const ApiMcpToolsRouteChildren: ApiMcpToolsRouteChildren = {
  ApiMcpToolsToolNameInvokeRoute: ApiMcpToolsToolNameInvokeRoute,
  ApiMcpToolsToolNameSchemaRoute: ApiMcpToolsToolNameSchemaRoute,
}

const ApiMcpToolsRouteWithChildren = ApiMcpToolsRoute._addFileChildren(
  ApiMcpToolsRouteChildren,
)

interface ApiMemoriesMemoryIdRouteChildren {
  ApiMemoriesMemoryIdRateRoute: typeof ApiMemoriesMemoryIdRateRoute
  ApiMemoriesMemoryIdSimilarRoute: typeof ApiMemoriesMemoryIdSimilarRoute
}

const ApiMemoriesMemoryIdRouteChildren: ApiMemoriesMemoryIdRouteChildren = {
  ApiMemoriesMemoryIdRateRoute: ApiMemoriesMemoryIdRateRoute,
  ApiMemoriesMemoryIdSimilarRoute: ApiMemoriesMemoryIdSimilarRoute,
}

const ApiMemoriesMemoryIdRouteWithChildren =
  ApiMemoriesMemoryIdRoute._addFileChildren(ApiMemoriesMemoryIdRouteChildren)

interface ApiNotificationsIdRouteChildren {
  ApiNotificationsIdReadRoute: typeof ApiNotificationsIdReadRoute
}

const ApiNotificationsIdRouteChildren: ApiNotificationsIdRouteChildren = {
  ApiNotificationsIdReadRoute: ApiNotificationsIdReadRoute,
}

const ApiNotificationsIdRouteWithChildren =
  ApiNotificationsIdRoute._addFileChildren(ApiNotificationsIdRouteChildren)

interface ApiGhostsConversationsConversationIdMessagesRouteChildren {
  ApiGhostsConversationsConversationIdMessagesStreamRoute: typeof ApiGhostsConversationsConversationIdMessagesStreamRoute
}

const ApiGhostsConversationsConversationIdMessagesRouteChildren: ApiGhostsConversationsConversationIdMessagesRouteChildren =
  {
    ApiGhostsConversationsConversationIdMessagesStreamRoute:
      ApiGhostsConversationsConversationIdMessagesStreamRoute,
  }

const ApiGhostsConversationsConversationIdMessagesRouteWithChildren =
  ApiGhostsConversationsConversationIdMessagesRoute._addFileChildren(
    ApiGhostsConversationsConversationIdMessagesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  FriendsRoute: FriendsRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  VoidRoute: VoidRoute,
  ApiNotificationsWsRoute: ApiNotificationsWsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWsRoute: ApiWsRoute,
  DmLinksCodeRoute: DmLinksCodeRoute,
  FriendLinksCodeRoute: FriendLinksCodeRoute,
  GroupLinksCodeRoute: GroupLinksCodeRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiConversationsConversationIdRoute:
    ApiConversationsConversationIdRouteWithChildren,
  ApiGroupsGroupIdRoute: ApiGroupsGroupIdRouteWithChildren,
  ApiMcpToolsRoute: ApiMcpToolsRouteWithChildren,
  ApiMemoriesMemoryIdRoute: ApiMemoriesMemoryIdRouteWithChildren,
  ApiMemoriesCheckDuplicateRoute: ApiMemoriesCheckDuplicateRoute,
  ApiMemoriesFeedRoute: ApiMemoriesFeedRoute,
  ApiMemoriesSearchRoute: ApiMemoriesSearchRoute,
  ApiNotificationsIdRoute: ApiNotificationsIdRouteWithChildren,
  ApiNotificationsReadAllRoute: ApiNotificationsReadAllRoute,
  ApiNotificationsUnreadCountRoute: ApiNotificationsUnreadCountRoute,
  ApiRelationshipsRelatedUserIdRoute: ApiRelationshipsRelatedUserIdRoute,
  ApiSpacesFeedRoute: ApiSpacesFeedRoute,
  ApiUsersSearchRoute: ApiUsersSearchRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiDmLinksIndexRoute: ApiDmLinksIndexRoute,
  ApiFriendLinksIndexRoute: ApiFriendLinksIndexRoute,
  ApiGhostsIndexRoute: ApiGhostsIndexRoute,
  ApiGroupsIndexRoute: ApiGroupsIndexRoute,
  ApiMemoriesIndexRoute: ApiMemoriesIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiRelationshipsIndexRoute: ApiRelationshipsIndexRoute,
  ApiDmLinksCodeRedeemRoute: ApiDmLinksCodeRedeemRoute,
  ApiFriendLinksCodeRedeemRoute: ApiFriendLinksCodeRedeemRoute,
  ApiGhostsGhostIdConversationRoute: ApiGhostsGhostIdConversationRoute,
  ApiGroupLinksCodeRedeemRoute: ApiGroupLinksCodeRedeemRoute,
  ApiGhostsConversationsIndexRoute: ApiGhostsConversationsIndexRoute,
  ApiGhostsConversationsConversationIdMessagesRoute:
    ApiGhostsConversationsConversationIdMessagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
